# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ciudad Luz - Energía Solar Distribuida Para Chile y Sudamérica
email: contacto@ciudadluz.cl
description: Toma el control de tu energía con Ciudad Luz y sus servicios de energía solar para hogares, empresas y servicios públicos. LIVE. 00:00. 01:12. Like.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ciudadluz.cl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
lang: es

google_analytics: UA-NNNNNNNN-N

collections:
  novedades:
    output: true
    permalink: /:collection/:name
  projects_residencial:
    output: true
    permalink: /:collection/:name
  projects_residencial_mapa:
    output: true
  projects_empresarial:
    output: true
    permalink: /:collection/:name
  projects_empresarial_mapa:
    output: true
  projects_institucional:
    output: true
    permalink: /:collection/:name
  projects_institucional_mapa:
    output: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
